sudo: required
services:
  - docker

before_install:
  - docker build -t cpjohnston/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cpjohnston/react-test npm run test

after_success:
  - docker build -t cpjohnston/multi-client ./client
  - docker build -t cpjohnston/multi-nginx ./nginx
  - docker build -t cpjohnston/multi-server ./server
  - docker build -t cpjohnston/multi-worker ./worker
  - echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cpjohnston/multi-client
  - docker push cpjohnston/multi-nginx
  - docker push cpjohnston/multi-server
  - docker push cpjohnston/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-529981329863
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY